version: "3.8"

services:
  app:
    build: .
    container_name: myapp
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env
    environment:
      - APP_ENV=${APP_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_DATABASE}
    network_mode: "bridge"
    restart: unless-stopped
